--- 

- name: Extract artifact to ec2 
  become: true
  unarchive: 
    src: artifact.tar.gz
    dest: .

- name: Start app 
  become: true 
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start